name: DuckDB extension
on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  distribution:
    uses: duckdb/extension-ci-tools/.github/workflows/_extension_distribution.yml@v1.5.0
    with:
      duckdb_version: v1.5.2
      ci_tools_version: v1.5.0
      extension_name: duckclinvarbitration
      extra_toolchains: python3
      exclude_archs: windows_amd64;windows_arm64
      reduced_ci_mode: disabled
